micronaut:
  application:
    name: efficientTestStartupKotest

mongodb:
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}

netty:
  default:
    allocator:
      max-order: 3

repository:
  databaseName: "application"
  articleCollectionName: "articles"
  productCollectionName: "products"
